import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { createTestSession, expect, test } from "./fixtures";

test.describe("team membership and settings", () => {
  let owner: Awaited<ReturnType<typeof createTestSession>>;
  let admin: Awaited<ReturnType<typeof createTestSession>>;
  let member: Awaited<ReturnType<typeof createTestSession>>;
  let otherAdmin: Awaited<ReturnType<typeof createTestSession>>;
  let runSql: (sql: string) => void;
  let teamId: string;
  test.beforeEach(async ({ context }) => {
    owner = await createTestSession("Team owner");
    admin = await createTestSession("Team admin");
    member = await createTestSession("Regular member");
    otherAdmin = await createTestSession("Other admin");
    await context.clearCookies(); await context.addCookies([owner.cookie]);
    const { name } = JSON.parse(await readFile("playwright/.cache/test-web-database.json", "utf8"));
    runSql = sql => execFileSync("docker", ["exec", "-u", "postgres", name, "psql", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-c", sql], { stdio: "ignore" });
    teamId = randomUUID();
    runSql(`INSERT INTO teams(id,name,description,owner_user_id) VALUES ('${teamId}','Managed team','Team description','${owner.userId}');
      INSERT INTO team_members(team_id,user_id,role) VALUES ('${teamId}','${owner.userId}','member'),('${teamId}','${admin.userId}','admin'),
      ('${teamId}','${member.userId}','member'),('${teamId}','${otherAdmin.userId}','admin');`);
  });
  test.afterEach(() => { owner?.remove(); admin?.remove(); member?.remove(); otherAdmin?.remove(); });

  test("Owner saves row roles and confirms named member removal; Cancel and Escape preserve membership", async ({ page }, testInfo) => {
    await page.goto(`/teams/${teamId}/members`);
    const row = page.getByRole("row").filter({ has: page.getByRole("cell", { name: "Regular member", exact: true }) });
    await expect(row.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
    await row.getByLabel("Role for Regular member").selectOption("admin");
    await row.getByRole("button", { name: "Save", exact: true }).click();
    await expect(row.getByLabel("Role for Regular member")).toHaveValue("admin");
    await expect(row.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
    await page.reload();
    await expect(row.getByLabel("Role for Regular member")).toHaveValue("admin");
    await row.getByLabel("Role for Regular member").selectOption("member");
    await row.getByRole("button", { name: "Save", exact: true }).click();
    await expect(row.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
    await page.screenshot({ path: testInfo.outputPath("team-members-desktop.png"), fullPage: true });
    const trigger = page.getByRole("button", { name: "Remove Team admin", exact: true });
    await trigger.click();
    const dialog = page.getByRole("dialog", { name: "Remove Team admin?", exact: true });
    await expect(dialog).toContainText("Managed team");
    const bounds = await dialog.boundingBox();
    expect(bounds).not.toBeNull();
    expect(Math.abs(bounds!.x + bounds!.width / 2 - page.viewportSize()!.width / 2)).toBeLessThan(2);
    await expect(dialog.getByRole("button", { name: "Cancel" })).toBeFocused();
    await page.keyboard.press("Escape");
    await expect(dialog).toBeHidden();
    await expect(trigger).toBeFocused();
    await trigger.click();
    await dialog.getByRole("button", { name: "Cancel" }).click();
    await expect(trigger).toBeVisible();
    await trigger.click();
    await page.screenshot({ path: testInfo.outputPath("remove-member-dialog.png"), fullPage: true });
    await dialog.getByRole("button", { name: "Remove member", exact: true }).click();
    await expect(page.getByRole("cell", { name: "Team admin", exact: true })).toHaveCount(0);
    await page.reload();
    await expect(page.getByRole("cell", { name: "Team admin", exact: true })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Remove Team owner", exact: true })).toHaveCount(0);
  });

  test("Admin manages regular Members and settings; Members see read-only controls and confirm leaving", async ({ page, context }, testInfo) => {
    await context.clearCookies(); await context.addCookies([admin.cookie]);
    await page.goto(`/teams/${teamId}/members`);
    await expect(page.getByRole("combobox")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Remove Other admin" })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Remove Regular member" })).toBeVisible();
    await page.goto(`/teams/${teamId}/settings`);
    await page.getByLabel("Team name").fill("Admin renamed");
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Team details saved.");
    await expect(page.getByRole("button", { name: "Transfer ownership", exact: true })).toHaveCount(0);
    await context.clearCookies(); await context.addCookies([member.cookie]);
    await page.goto(`/teams/${teamId}/settings`);
    await expect(page.getByLabel("Team name")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Save changes", exact: true })).toHaveCount(0);
    await expect(page.getByText("The Owner and Admins manage these details.")).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole("main").getByRole("button", { name: "Leave team…", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Leave Admin renamed?", exact: true });
    await expect(dialog).toContainText("all its projects and requirements");
    await dialog.getByRole("button", { name: "Cancel" }).click();
    await page.getByRole("main").getByRole("button", { name: "Leave team…", exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath("leave-team-mobile.png"), fullPage: true });
    await dialog.getByRole("button", { name: "Leave team", exact: true }).click();
    await expect(page).toHaveURL(/\/teams$/);
    await page.goto(`/teams/${teamId}/members`);
    await expect(page.getByRole("heading", { name: "Team not found" })).toBeVisible();
    await page.goto("/onboarding");
    await expect(page).toHaveURL(/\/teams$/); // Leaving does not reset completed onboarding.
  });

  test("Owner saves validated settings, transfers to a regular Member, then leaves from the team menu", async ({ page }, testInfo) => {
    await page.goto(`/teams/${teamId}/settings`);
    await page.getByLabel("Team name").fill(" ");
    await page.getByLabel("Description").fill("Keep these details");
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByLabel("Team name")).toHaveAttribute("aria-invalid", "true");
    await expect(page.getByLabel("Description")).toHaveValue("Keep these details");
    await page.getByLabel("Team name").fill("Updated team");
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Team details saved.");
    await expect(page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Updated team", exact: true })).toBeVisible();
    // A second successful save must refresh the sidebar too, even when success stays true.
    await page.getByLabel("Team name").fill("Updated again");
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Updated again", exact: true })).toBeVisible();
    await page.getByLabel("Team name").fill("Updated team");
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Updated team", exact: true })).toBeVisible();
    await page.getByRole("main").getByRole("button", { name: "Leave team…", exact: true }).click();
    const blocked = page.getByRole("dialog", { name: "Leave Updated team?", exact: true });
    await expect(blocked.getByRole("button", { name: "Leave team", exact: true })).toBeDisabled();
    await expect(blocked).toContainText("Transfer ownership before leaving");
    await blocked.getByRole("button", { name: "Cancel" }).click();
    await page.getByLabel("New Owner").selectOption(member.userId);
    await page.getByRole("main").getByRole("button", { name: "Transfer ownership", exact: true }).click();
    const transfer = page.getByRole("dialog", { name: "Transfer ownership of Updated team?", exact: true });
    await expect(transfer).toContainText("Regular member");
    await expect(transfer).toContainText("You’ll become an Admin");
    await transfer.getByRole("button", { name: "Cancel" }).click();
    await page.getByRole("main").getByRole("button", { name: "Transfer ownership", exact: true }).click();
    await page.screenshot({ path: testInfo.outputPath("transfer-team-desktop.png"), fullPage: true });
    await transfer.getByRole("button", { name: "Transfer ownership", exact: true }).click();
    await expect(page.getByText("Only the Owner can transfer ownership.", { exact: true })).toBeVisible();
    await expect(page.getByText("Regular member owns this team.", { exact: true })).toBeVisible();
    await page.goto(`/teams/${teamId}`);
    await expect(page.locator("dd").first()).toHaveText("Admin");
    const group = page.getByRole("region", { name: "Updated team", exact: true });
    await group.getByRole("button", { name: "Team actions for Updated team" }).click();
    await group.getByRole("button", { name: "Leave team…", exact: true }).click();
    const leave = page.getByRole("dialog", { name: "Leave Updated team?", exact: true });
    await expect(leave.getByRole("button", { name: "Leave team", exact: true })).toBeEnabled();
    await leave.getByRole("button", { name: "Leave team", exact: true }).click();
    await expect(page).toHaveURL(/\/teams$/);
    await expect(page.getByRole("list", { name: "Your teams" }).getByRole("link", { name: /Updated team/ })).toHaveCount(0);
  });
});
