import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { createTestSession, expect, test } from "./fixtures";

test.describe("team invitations", () => {
  let owner: Awaited<ReturnType<typeof createTestSession>>;
  let recipient: Awaited<ReturnType<typeof createTestSession>>;
  let admin: Awaited<ReturnType<typeof createTestSession>>;
  let runSql: (sql: string) => void;
  let teamId: string;
  test.beforeEach(async ({ context }) => {
    owner = await createTestSession("Invitation owner");
    recipient = await createTestSession("Invited person", false);
    admin = await createTestSession("Invitation admin");
    await context.clearCookies(); await context.addCookies([owner.cookie]);
    const { name } = JSON.parse(await readFile("playwright/.cache/test-web-database.json", "utf8"));
    runSql = sql => execFileSync("docker", ["exec", "-u", "postgres", name, "psql", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-c", sql], { stdio: "ignore" });
    teamId = randomUUID();
    runSql(`INSERT INTO teams(id,name,description,owner_user_id) VALUES ('${teamId}','Inviting team','Work together','${owner.userId}');
      INSERT INTO team_members(team_id,user_id,role) VALUES ('${teamId}','${owner.userId}','member'),('${teamId}','${admin.userId}','admin');`);
  });
  test.afterEach(() => { owner?.remove(); recipient?.remove(); admin?.remove(); });

  test("Members dialog issues a copyable link; signed-out signup keeps it; verified acceptance completes onboarding without creating another team", async ({ page, context }, testInfo) => {
    await context.grantPermissions(["clipboard-read", "clipboard-write"]);
    await page.goto(`/teams/${teamId}/members`);
    await page.getByRole("button", { name: "Invite people", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Invite people", exact: true });
    await expect(dialog.getByLabel("Email", { exact: true })).toBeFocused();
    await dialog.getByLabel("Email", { exact: true }).fill(`${recipient.userId}@example.invalid`);
    await dialog.getByRole("combobox", { name: "Role", exact: true }).selectOption("member");
    await page.screenshot({ path: testInfo.outputPath("invite-people-desktop.png"), fullPage: true });
    await dialog.getByLabel("Email", { exact: true }).fill(`${admin.userId}@example.invalid`);
    await dialog.getByRole("combobox", { name: "Role", exact: true }).selectOption("admin");
    await dialog.getByRole("button", { name: "Send invitation" }).click();
    await expect(dialog.getByRole("alert")).toContainText("already a team member");
    await expect(dialog.getByLabel("Email", { exact: true })).toHaveValue(`${admin.userId}@example.invalid`);
    await expect(dialog.getByRole("combobox", { name: "Role", exact: true })).toHaveValue("admin");
    await dialog.getByLabel("Email", { exact: true }).fill(`${recipient.userId}@example.invalid`);
    await dialog.getByRole("combobox", { name: "Role", exact: true }).selectOption("member");
    await dialog.getByRole("button", { name: "Send invitation" }).click();
    await expect(dialog.getByRole("status")).toContainText("Invitation email sent");
    const link = await dialog.getByLabel("Invitation link", { exact: true }).inputValue();
    expect(new URL(link).pathname).toMatch(/^\/invites\/[a-f0-9]{64}$/);
    await dialog.getByRole("button", { name: "Copy link", exact: true }).click();
    await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(link);
    await dialog.getByRole("button", { name: "Done" }).click();
    await expect(page.getByRole("cell", { name: "Invited person", exact: true })).toHaveCount(0);
    await context.clearCookies();
    await page.goto(link);
    await expect(page.getByRole("heading", { name: "You’re invited to a team" })).toBeVisible();
    await expect(page.locator(".app-sidebar, .site-header")).toHaveCount(0);
    const next = encodeURIComponent(new URL(link).pathname);
    await expect(page.getByRole("link", { name: "Sign in", exact: true })).toHaveAttribute("href", `/login?next=${next}`);
    await page.getByRole("link", { name: "Create account", exact: true }).click();
    await expect(page).toHaveURL(new RegExp(`/signup\\?next=${next}$`));
    await expect(page.getByRole("main").getByRole("link", { name: "Log in", exact: true })).toHaveAttribute("href", `/login?next=${next}`);
    await context.addCookies([recipient.cookie]);
    await page.goto("/projects");
    await expect(page).toHaveURL(/\/onboarding$/);
    await page.goto(link);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole("button", { name: "Accept invitation" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Name your first team" })).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath("accept-invitation-mobile.png"), fullPage: true });
    await page.getByRole("button", { name: "Accept invitation" }).click();
    await expect(page).toHaveURL(new RegExp(`/teams/${teamId}$`));
    await expect(page.getByRole("heading", { name: "Inviting team", level: 1 })).toBeVisible();
    await page.goto("/onboarding");
    await expect(page).toHaveURL(/\/teams$/);
    await expect(page.getByRole("list", { name: "Your teams" }).getByRole("link")).toHaveCount(1);
    await page.goto(`/teams/${teamId}/members`);
    await expect(page.getByRole("cell", { name: "Invited person", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Invite people" })).toHaveCount(0);
    await page.goto(link);
    await expect(page.getByRole("link", { name: "Open team" })).toHaveAttribute("href", `/teams/${teamId}`);
  });

  test("table resends invalidate earlier links; revocation uses a named confirmation; expired links keep onboarding required", async ({ page, context }, testInfo) => {
    await page.goto(`/teams/${teamId}/invitations`);
    await expect(page.getByRole("heading", { name: "No invitations yet" })).toBeVisible();
    await page.getByRole("button", { name: "Invite people", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Invite people", exact: true });
    await dialog.getByLabel("Email", { exact: true }).fill(`${recipient.userId}@example.invalid`);
    await dialog.getByRole("button", { name: "Send invitation" }).click();
    await expect(dialog.getByLabel("Invitation link")).toBeVisible();
    const oldLink = await dialog.getByLabel("Invitation link").inputValue();
    await dialog.getByRole("button", { name: "Done" }).click();
    const row = page.getByRole("row").filter({ has: page.getByRole("cell", { name: `${recipient.userId}@example.invalid`, exact: true }) });
    await expect(row.getByRole("cell", { name: "Pending", exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("team-invitations-desktop.png"), fullPage: true });
    await row.getByRole("button", { name: "Resend", exact: true }).click();
    await expect(row.getByLabel("Invitation link")).toBeVisible();
    const fresh = await row.getByLabel("Invitation link").inputValue();
    expect(fresh).not.toBe(oldLink);
    await row.getByRole("button", { name: "Revoke", exact: true }).click();
    const confirmation = page.getByRole("dialog", { name: "Revoke invitation", exact: true });
    await expect(confirmation).toContainText(`${recipient.userId}@example.invalid`);
    await confirmation.getByRole("button", { name: "Cancel" }).click();
    await expect(row.getByRole("cell", { name: "Pending", exact: true })).toBeVisible();
    await row.getByRole("button", { name: "Revoke", exact: true }).click();
    await confirmation.getByRole("button", { name: "Revoke invitation", exact: true }).click();
    await expect(row.getByRole("cell", { name: "Revoked", exact: true })).toBeVisible();
    await expect(row.getByRole("button", { name: "Resend", exact: true })).toHaveCount(0);
    await page.getByRole("button", { name: "Invite people", exact: true }).click();
    await dialog.getByLabel("Email", { exact: true }).fill(`${recipient.userId}@example.invalid`);
    await dialog.getByRole("button", { name: "Send invitation" }).click();
    await expect(dialog.getByLabel("Invitation link")).toBeVisible();
    const expired = await dialog.getByLabel("Invitation link").inputValue();
    await dialog.getByRole("button", { name: "Done" }).click();
    runSql(`UPDATE team_invitations SET issued_at=now()-interval '8 days',expires_at=now()-interval '1 day' WHERE team_id='${teamId}' AND revoked_at IS NULL;`);
    await context.clearCookies(); await context.addCookies([recipient.cookie]);
    for (const [link, message] of [[oldLink, "This link is invalid or has been replaced."], [fresh, "This invitation has been revoked."], [expired, "This invitation has expired."]]) {
      await page.goto(link);
      await expect(page.getByRole("heading", { name: "Invitation unavailable" })).toBeVisible();
      await expect(page.getByText(message, { exact: false })).toBeVisible();
      await expect(page.getByRole("button", { name: "Accept invitation" })).toHaveCount(0);
    }
    await page.goto("/teams");
    await expect(page).toHaveURL(/\/onboarding$/);
  });

  test("Admins invite Members only; permission loss blocks joining and wrong accounts can switch without bypassing onboarding", async ({ page, context }) => {
    await context.clearCookies(); await context.addCookies([admin.cookie]);
    await page.goto(`/teams/${teamId}/members`);
    await page.getByRole("button", { name: "Invite people", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Invite people", exact: true });
    await expect(dialog.getByRole("combobox", { name: "Role", exact: true }).locator("option")).toHaveText(["Member"]);
    await dialog.getByLabel("Email", { exact: true }).fill(`${recipient.userId}@example.invalid`);
    await dialog.getByRole("button", { name: "Send invitation" }).click();
    await expect(dialog.getByLabel("Invitation link")).toBeVisible();
    const link = await dialog.getByLabel("Invitation link").inputValue();
    await dialog.getByRole("button", { name: "Done" }).click();
    await page.goto(link);
    await expect(page.getByText(`You’re signed in as ${admin.userId}@example.invalid.`, { exact: false })).toBeVisible();
    await expect(page.getByRole("button", { name: "Accept invitation" })).toHaveCount(0);
    await page.getByRole("button", { name: "Use another account" }).click();
    await expect(page).toHaveURL(/\/login\?next=%2Finvites%2F/);
    await context.addCookies([recipient.cookie]);
    runSql(`UPDATE team_members SET role='member' WHERE team_id='${teamId}' AND user_id='${admin.userId}';`);
    await page.goto(link);
    await expect(page.getByText("The inviter no longer has permission to invite you.", { exact: false })).toBeVisible();
    await expect(page.getByRole("button", { name: "Accept invitation" })).toHaveCount(0);
    await page.goto("/dashboard");
    await expect(page).toHaveURL(/\/onboarding$/);
  });
});
